<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>yang</string>
	</array>
	<key>name</key>
	<string>YANG</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>comments</string>
			<key>match</key>
			<string>(//.*$)</string>
			<key>name</key>
			<string>comment.yang</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>comments</string>
			<key>match</key>
			<string>(\s*(module|container|grouping|leaf|leaf-list|list|choice|revision|rpc|typedef|augment) +([a-zA-Z0-9;:\-_]+))\s*\{</string>
			<key>name</key>
			<string>block.yang</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([\"\'])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>([\"\'];)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.yang</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.quoted.double</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)\b(
				anyxml|argument|augment|base|belongs-to|bit|case|choise|config|contact|
				container|default|description|deviate|deviation|enum|error-app-tag|
				error-message|extension|feature|fraction-digits|grouping|identity|if-feature|
				import|include|input|key|leaf|leaf-list|length|list|mandatory|module|must|
				namespace|notification|ordered-by|organization|output|path|pattern|position|
				prefix|presence|range|reference|refine|require-instance|revision|
				revision-date|rpc|status|submodule|type|typedef|unique|units|uses|value|when|
				yang-version|yin-element
			)\b</string>
			<key>name</key>
			<string>support.function.builtin.yang</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)\b(
				binary|bits|boolean|decimal64|empty|enumeration|identityref|instance-identifier|
				int8|int16|int32|int64|leafref|string|uint8|uint16|uint32|uint64|union
			)\b</string>
			<key>name</key>
			<string>storage.type.yang</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.yang</string>
	<key>uuid</key>
	<string>9ef30d21-cb3f-4665-b28e-23175f3c3376</string>
</dict>
</plist>
